# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hostname", color = "(YW)"}
# uptime    = {icon = " ", name = "uptime", color = "(BE)"}
# distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
# desktop   = {icon = "󰟀 ", name = "desktop", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(RD)"}
# shell     = {icon = " ", name = "shell", color = "(YW)"}
packages  = {icon = " ", name = "packages", color = "(BE)"}  # WARNING: Resource Intensive
# weather   = {icon = " ", name = "weather", color = "(GN)"} # Requires curl and an emoji font. | WARNING: Resource Intensive
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}      # WARNING: Resource Intensive
# cpu       = {icon = " ", name = "cpu", color = "(GN)"}
# battery   = {icon = " ", name = "battery", color = "(MA)"}
memory    = {icon = " ", name = "memory", color = "(CN)"}
# The following stats do not work on MacOS and the BSDs.
disk_0    = {icon = " ", name = "disk", color = "(RD)"}
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
location = "" # Used for fetching weather; leave empty to use the location of your IP; check https://wttr.in/:help for supported location types
# stats_margin_top = 0

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = true
path   = "/home/sybil/wallpapers/imgs/temp.png" # Please only use absolute paths.
scale  = 20
margin = [3, 2, 1,]

